from pwn import *

#p = process('./intro')
p = remote('plsdonthaq.me', 1025)
p.recvuntil('{')
num = p.recvuntil('}', drop=True)
num_dec = int(num, 16)
p.sendline(str(num_dec))
p.recvuntil('MINUS ')
new_hex = hex(num_dec - int(p.recvuntil('!', drop=True), 16))
p.sendline(new_hex)
p.recvlines(3)
little_endian = p32(num_dec)
p.sendline(little_endian)
little_endian_to_int = u32(p.recvlines(3)[-1])
little_endian_to_hex = hex(little_endian_to_int)
p.recvline()
p.sendline(str(little_endian_to_int))
p.recvlines(3)
p.sendline(little_endian_to_hex)
sum_problem = p.recvlines(2)[-1][:-1].split()
sum_sol = int(sum_problem[-3]) + int(sum_problem[-1])
p.sendline(str(sum_sol))
p.recvlines(3)
p.sendline('password')
print(p.recv())
p.interactive()
